required = [
  "golang.org/x/lint/golint"
]

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  revision = "470b6b0bb3005eda157f0275e2e4895055396a81"
  name = "golang.org/x/lint"
